nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.4.cjs

httpProxy: "http://192.168.49.1:8000"
httpsProxy: "http://192.168.49.1:8000"

packageExtensions:
  "@react-native/babel-plugin-codegen@*":
    dependencies:
      "@babel/preset-env": "*"
      "@babel/core": "*"

  "babel-plugin-transform-flow-enums@*":
    peerDependencies:
      "@babel/core": "*"

  "nativewind@*":
    peerDependencies:
      "react": "*"
      "react-native": "*"
      "react-native-reanimated": "*"

  "react-native@*":
    peerDependencies:
      "@babel/preset-env": "*"